<?php
return [
    'GET /' => ['AuthController', 'landing'],
    'GET /login' => ['AuthController', 'showLogin'],
    'POST /login' => ['AuthController', 'login'],
    'POST /logout' => ['AuthController', 'logout'],

    'GET /admin' => ['DashboardController', 'admin'],
    'GET /worker' => ['DashboardController', 'worker'],

    'GET /monitor' => ['MonitorController', 'view'],
    'GET /monitor/data' => ['MonitorController', 'ajax'],
    'POST /ingesta' => ['MonitorController', 'ingesta'],

    'GET /historico' => ['HistoricoController', 'filtros'],
    'POST /historico/graficos' => ['HistoricoController', 'graficos'],

    'GET /soporte' => ['SoporteController', 'menu'],
    'GET /soporte/admin' => ['SoporteController', 'listarAbiertos'],
    'GET /soporte/problema' => ['SoporteController', 'obtenerProblema'],
    'POST /soporte/cerrar' => ['SoporteController', 'cerrar'],
    'GET /soporte/mis' => ['SoporteController', 'misTickets'],
    'GET /soporte/respuesta' => ['SoporteController', 'obtenerRespuesta'],
    'GET /soporte/crear' => ['SoporteController', 'crearForm'],
    'POST /soporte/crear' => ['SoporteController', 'crear'],

    'GET /cuentas' => ['CuentaController', 'menu'],
    'GET /cuentas/crear' => ['CuentaController', 'crearForm'],
    'POST /cuentas/crear' => ['CuentaController', 'crear'],
    'GET /cuentas/editar' => ['CuentaController', 'editarForm'],
    'POST /cuentas/editar' => ['CuentaController', 'editar'],
    'GET /cuentas/usuario' => ['CuentaController', 'obtenerUsuario'],
    'POST /cuentas/guardar' => ['CuentaController', 'guardarEdicion'],
    'POST /cuentas/reset' => ['CuentaController', 'resetearContrasena'],

    'GET /micuenta' => ['UsuarioController', 'miCuentaForm'],
    'POST /micuenta' => ['UsuarioController', 'miCuenta'],

    // API para app móvil
    'POST /api/v1/login' => ['AuthApiController', 'login'],
    'POST /api/v1/logout' => ['AuthApiController', 'logout'],
    'GET /api/v1/me' => ['AuthApiController', 'me'],
    'GET /api/v1/monitor' => ['MonitorController', 'ajaxApi'],
    'POST /api/v1/ingesta' => ['MonitorController', 'ingesta'],
    'POST /api/v1/change-password' => ['AuthApiController', 'changePassword'],
    'GET /api/v1/historico' => ['HistoricoController', 'api'],
    'GET /api/v1/soporte/mis' => ['AuthApiController', 'misTicketsApi'],
    'POST /api/v1/soporte/new' => ['SoporteController', 'crearApi'],
    'POST /api/v1/cuentas/desactivar' => ['AuthApiController', 'deactivateUser'],

    'GET /api/v1/cuentas/editar' => ['AuthApiController', 'cuentasEditarFormApi'],
    'POST /api/v1/cuentas/editar' => ['AuthApiController', 'editarApi'],
    'GET /api/v1/cuentas/crear' => ['AuthApiController', 'crearFormApi'],
    'POST /api/v1/cuentas/crear' => ['AuthApiController', 'crearApi'],
    'GET /api/v1/cuentas/usuario/{id}' => ['AuthApiController', 'cuentasObtenerUsuarioApi'],
    'POST /api/v1/cuentas/guardar' => ['AuthApiController', 'guardarEdicionApi'],
    'POST /api/v1/cuentas/reset' => ['AuthApiController', 'resetearContrasenaApi'],
    'GET /api/v1/soporte/admin' => ['AuthApiController', 'listarAbiertosApi'],
    'GET /api/v1/soporte/problema/{id}' => ['AuthApiController', 'obtenerProblemaApi'],
    'POST /api/v1/soporte/cerrar' => ['AuthApiController', 'cerrarApi'],
    'GET /api/v1/soporte/respuesta/{id}' => ['AuthApiController', 'obtenerRespuestaApi'],
    'GET /api/v1/soporte/crear' => ['AuthApiController', 'crearFormApi'],
    'POST /api/v1/soporte/crear' => ['AuthApiController', 'crearApi'],
    'GET /api/v1/micuenta' => ['AuthApiController', 'miCuentaFormApi'],
    'POST /api/v1/micuenta' => ['AuthApiController', 'miCuentaApi'],
    'GET /api/v1/admin' => ['AuthApiController', 'adminApi'],
    'GET /api/v1/worker' => ['AuthApiController', 'workerApi'],
    'POST /api/v1/historico/graficos' => ['AuthApiController', 'graficosApi'],
    'GET /api/v1/soporte' => ['AuthApiController', 'soporteMenuApi'],
    'GET /api/v1/cuentas' => ['AuthApiController', 'cuentasMenuApi'],
    'GET /api/v1/landing' => ['AuthApiController', 'landingApi'],
    'GET /api/v1/login' => ['AuthApiController', 'showLoginApi'],
    'GET /api/v1/monitor/view' => ['AuthApiController', 'monitorViewApi'],
    'GET /api/v1/monitor/data' => ['AuthApiController', 'monitorDataApi'],
    'GET /api/v1/historico/filtros' => ['AuthApiController', 'historicoFiltrosApi'],
];
